(global-set-key (kbd "M-g")
 (defhydra hydra-zoom ()
   "goto"
   ("TAB" move-to-column "column")
   ("N" first-error "first")
   ("n" next-error "next")
   ("p" previous-error "prev")
   ("g" goto-line "goto-line" :color blue)
   ("c" goto-char "goto-char" :color blue)
   ("q" nil "quit")))


(global-set-key (kbd "C-M-o")
 (defhydra hydra-window ()
   "window"
   ("n" windmove-down)
   ("p" windmove-up)
   ("f" windmove-right)
   ("b" windmove-left)
   ("3" (lambda ()
          (interactive)
          (split-window-right)
          (windmove-right)) :color blue)
   ("2" (lambda ()
          (interactive)
          (split-window-below)
          (windmove-down)) :color blue)
   ("0" delete-window "delete")
   ("q" nil "quit")
   ))
